/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { ERCInterface } from "./ERCInterface";

export { ERC20__factory } from "./factories/ERC20__factory";
export { ERCInterface__factory } from "./factories/ERCInterface__factory";
